config/routes.rb
Rails.application.routes.draw do
  resources :rentals
  resources :comments do
    member do
      post :new
    end
  end
  resources :products

  devise_for :users

  get "profile/:id", to: "profile#profile", as: "profile"
  get "profile/:id/rentals", to: "profile#rentals", as: "profile_rentals"
  post "rental/done/:id", to: "rentals#set_done", as: "rental_done"
  post "like/:product_id", to: "like#create", as: "like"
  post "dislike/:product_id", to: "dislike#create", as: "dislike"

  get "home", to: "home#index", as: "home"

  # Defines the root path route ("/")
  root "products#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :product, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :new
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :set_product, except: [:index, :create]


  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @product.comments.build
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update("btn_add_comment", partial: "comments/form", locals: {comment: @comment})
        ]
      end
    end
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    logger.debug "Logg"
    @comment = current_user.comments.new(comment_params)


    respond_to do |format|
      if @comment.save
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update("btn_add_comment", partial: "comments/new_comment_btn", locals:{ product: @comment.product }),
            turbo_stream.prepend("comments", @comment, locals:{ comment: @comment})
          ]
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :product_id)
    end

  def set_product
    @product = Product.find(params[:product_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>" class="card mt-2">

<div class="card-body">

  <h5 class="card-title">
    <%= link_to comment.user.first_name + " " + comment.user.last_name, profile_path(comment.user), style:"text-decoration:none;color:black;"%>
  </h5>

  <p>
    <%= comment.content %>
  </p>

  <p class="text-muted">
    Posted <%= time_ago_in_words comment.created_at %> ago
  </p>

</div>



</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label "New comment", style: "display: block" %>
    <%= form.text_area :content, class:"w-100 h-25"%>
  </div>

  <div style="display: none">
    <%= form.number_field :product_id, class:"w-100 h-25", value:comment.product.id %>
  </div>

  <div style="display: none">
    <%= form.number_field :user_id, class:"w-100 h-25", value:current_user.id%>
  </div>

  <div>
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/comments/_new_comment_btn.html.erb
<%= button_to "Add a comment", new_comment_path(product_id: product), class:"btn btn-primary", method: :post%>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>