config/routes.rb
Rails.application.routes.draw do
  resources :rentals
  resources :comments do
    member do
      post :new
    end
  end
  resources :products

  devise_for :users

  get "profile/:id", to: "profile#profile", as: "profile"
  get "profile/:id/rentals", to: "profile#rentals", as: "profile_rentals"
  post "rental/done/:id", to: "rentals#set_done", as: "rental_done"
  post "like/:product_id", to: "like#create", as: "like"
  post "dislike/:product_id", to: "dislike#create", as: "dislike"

  get "home", to: "home#index", as: "home"

  # Defines the root path route ("/")
  root "products#index"
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :product

  enum :status, {
    pending: 0,
    active: 1,
    done: 2
  }

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_rental, only: %i[ show edit update destroy set_done ]

  # GET /rentals or /rentals.json
  def index
    @rentals = Rental.all
  end

  # GET /rentals/1 or /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    product = Product.find(params[:product_id])
    @rental = product.rentals.new
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals or /rentals.json
  def create
    @rental = current_user.rentals.new(rental_params)

    if @rental.start_date == Date.current
      Rails.logger.debug "Today!! Set to active"
      @rental.active!
    end

    respond_to do |format|
      if @rental.save
        format.html { redirect_to rental_url(@rental), notice: "Rental was successfully created." }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1 or /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to rental_url(@rental), notice: "Rental was successfully updated." }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1 or /rentals/1.json
  def destroy
    @rental.destroy

    respond_to do |format|
      format.html { redirect_to rentals_url, notice: "Rental was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def set_done
    @rental.done!
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.remove(@rental),
          turbo_stream.prepend("done-rentals", @rental),
          turbo_stream.update("active-count", partial:"rentals/active_rentals_counter", locals:{active: @rental.user.rentals.where(status: :active)}),
          turbo_stream.update("done-count", partial:"rentals/done_rentals_counter", locals:{done: @rental.user.rentals.where(status: :done)}),
          turbo_stream.update("modal-body", partial: "rentals/rate_rental", locals:{rental: @rental})
        ]
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rental_params
      params.require(:rental).permit(:user_id, :product_id, :start_date, :end_date)
    end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/_active_rentals_counter.html.erb
<%= pluralize(active.count, 'active rental') %>

app/views/rentals/_done_rentals_counter.html.erb
<%= pluralize(done.count, 'finished rental') %>

app/views/rentals/_form.html.erb
<%= form_with(model: rental) do |form| %>
  <% if rental.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
        <% rental.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :user_id, type: :hidden %>
  </div>

  <div>
    <%= form.text_field :product_id, type: :hidden%>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rentals/_rate_rental.html.erb
<div class="container-fluid d-flex flex-column text-center">
  <h3 class="mt-3">Hope you enjoyed your stay!</h3>
  <h6 class="mt-3">How would you rate your stay?</h6>

  <div class="d-flex flex-row justify-content-center mt-4">
    <%= button_to dislike_path(rental.product), method: :post, hidden:true do %>
      <button type="submit" class="btn btn-danger mx-3" data-bs-toggle="modal" data-bs-target="#modal">
      <span class="material-icons">
        thumb_down
      </span>
      </button>
    <% end %>

    <%= button_to like_path(rental.product), method: :post, hidden:true do %>
      <button type="submit" class="btn btn-success mx-3" data-bs-toggle="modal" data-bs-target="#modal">
      <span class="material-icons">
        thumb_up
      </span>
      </button>
    <% end %>
  </div>

</div>

app/views/rentals/_rental.html.erb
  <div class="col" id="<%= dom_id rental %>">
    <div class="card">
      <%= link_to rental.product, class:"no-link" do %>
        <div class="card-body">
          <h5 class="card-title"><%= rental.product.title %></h5>
          <p class="card-text"><%= link_to rental.product.user.full_name, profile_path(rental.product.user), class:"no-link" %></p>
          <p class="card.text">Rental start: <%= rental.start_date %></p>
          <p class="card.text">Rental end: <%= rental.start_date %></p>
          <% if rental.user == current_user and rental.active? %>
            <%= button_to rental_done_path(rental), method: :post, hidden:true do%>
              <button type="submit" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal" id="btn_modal">
                Mark this rental as done
              </button>
            <% end %>
          <% end %>

          <% if rental.done? %>
            <p class="text-muted">Marked as done <%= time_ago_in_words rental.updated_at %> ago</p>
          <% end %>

        </div>
      <% end %>
    </div>
  </div>

app/views/rentals/edit.html.erb
<h1>Editing rental</h1>

<%= render "form", rental: @rental %>

<br>

<div>
  <%= link_to "Show this rental", @rental %> |
  <%= link_to "Back to rentals", rentals_path %>
</div>

app/views/rentals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rentals</h1>

<div id="rentals">
  <% @rentals.each do |rental| %>
    <%= render rental %>
    <p>
      <%= link_to "Show this rental", rental %>
    </p>
  <% end %>
</div>

app/views/rentals/new.html.erb
<h1>New rental</h1>

<%= render "form", rental: @rental %>

app/views/rentals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @rental %>