config/routes.rb
Rails.application.routes.draw do
  resources :rentals
  resources :comments do
    member do
      post :new
    end
  end
  resources :products

  devise_for :users

  get "profile/:id", to: "profile#profile", as: "profile"
  get "profile/:id/rentals", to: "profile#rentals", as: "profile_rentals"
  post "rental/done/:id", to: "rentals#set_done", as: "rental_done"
  post "like/:product_id", to: "like#create", as: "like"
  post "dislike/:product_id", to: "dislike#create", as: "dislike"

  get "home", to: "home#index", as: "home"

  # Defines the root path route ("/")
  root "products#index"
end

app/models/product.rb
class Product < ApplicationRecord

  has_one_attached :image, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_many :rentals, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy

  validate :acceptable_image


  def acceptable_image
    Rails.logger.debug "Sjekker om det er attached"
    if image.attached?
      Rails.logger.debug "Bildet er attached"
      acceptable_types = ["image/jpeg", "image/jpg", "image/png"]

      unless acceptable_types.include?(image.content_type)
        errors.add(:main_image, "must be a JPEG or PNG")
      end
    else
      self.image.attach(io: File.open(Rails.root.join("app", "assets", "images", "default.png")), filename: 'default.png' , content_type: "image/png  ")
    end
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all.order("created_at DESC")
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.products.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :content, :user_id, :image, :address, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block", class:"mt-4" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div>
    <%= form.label :address, style: "display: block", class:"mt-4" %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div>
    <%= form.label "Price per day ($)", style: "display: block", class:"mt-4" %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <div>
    <%= form.number_field :user_id, id: :story_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.label :content, style: "display: block", class:"mt-4" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <%= form.label :image, class:"mt-4" %>
  <%= form.file_field :image, class: "form-control" %>

  <div>
    <%= form.submit class:"btn btn-success mt-4" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="card border-0" id="<%= dom_id product %>">
  <div class="d-flex justify-content-center w-100">
      <%= image_tag product.image, class:"w-100" %>
    <li class="dropdown position-absolute top-0 end-0 mt-1" style="list-style-type: none;">
      <a href="#" class="nav-link" data-bs-toggle="dropdown" role="button" aria-expanded="false">
        <span class="material-icons" style="color:black;">more_vert</span>
      </a>
      <ul class="dropdown-menu dropdown-menu-end me-1">
        <% if user_signed_in? %>
          <!-- Edit story button -->
          <% if current_user.id == product.user_id %>
            <li>
              <%= link_to "Edit listing", edit_product_path(product), class: "dropdown-item" %>
            </li>
          <% end %>

          <li><%= %></li>

        <% else %>
          <li class="dropdown-item">Legg til i spilleliste</li>
        <% end %>
      </ul>
    </li>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-8">
        <h5 class="card-title"><%= product.title %></h5>
        <p class="card-subtitle text-muted mt-3" hidden>This listing is currently being rented</p>
        <h6 class="card-subtitle mt-3"><%= product.address %></h6>
        <p class="card-subtitle text-muted mt-3">Costs $<%= product.price %> a day</p>
        <p class="card-text mt-3"><%= product.content %></p>
        <p class="card-text mt-3">Listed by <%= link_to product.user.first_name + " " + product.user.last_name, profile_path(product.user) %></p>
      </div>

      <div class="col-4">
        <h5>This listing has been rented <%= pluralize product.rentals.count, 'time' %></h5>

        <div class="d-flex flex-row g-2 mt-3">
          <div class="d-flex flex-col">
            <div class="text-center">
              <span class="material-icons px-2 py-1 rounded bg-success mx-2" style="color:white">thumb_up</span>
              <p class="card-text mt-3"><%= product.likes.count %></p>
            </div>

            <div class="d-flex flex-col">
              <div class="text-center">
                <span class="material-icons px-2 py-1 rounded bg-danger mx-2" style="color:white">thumb_down</span>
                <p class="card-text mt-3"><%= product.dislikes.count %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/_profile_product.html.erb
<div class="col">
  <div class="card">
    <%= link_to product, class:"no-link" do %>
      <div class="d-flex justify-content-center w-100 bg-white">
        <%= image_tag product.image, class:"w-50 card-img-top"%>
      </div>


    <div class="card-body border-top">
      <h5 class="card-title" style="text-decoration: none"><%= product.title %></h5>
      <p class="card-text" style="text-decoration: none; color:black"><%= product.content.truncate(100) %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>
<%= link_to "Delete this listing", product_path(@product), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class:"btn btn-danger mt-4" %>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Available listings</h1>

<div id="products">
  <% @products.each do |product| %>

    <div class="card my-2 my-md-4" id="<%= dom_id product %>" >
      <div class="row g-0">
        <div class="col-md-4">
            <%= image_tag product.image, class:"img-fluid rounded-start h-100" %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><%= product.title %></h5>
            <p class="card-text"><%= product.content.truncate(180) %></p>
            <p class="card-subtitle text-muted mt-3">Costs $<%= product.price %> a day</p>
            <p class="card-text mt-1"><h6 class="mt-1"><%= link_to product.user.full_name, profile_path(product.user), class:"no-link" %></h6></p>
            <p class="text-muted">This listing has been rented <%= pluralize product.rentals.count, 'time' %></p>
            <%= link_to "Show this listing", product, class:"btn btn-primary" %>
            <p class="card-text mt-4"><small class="text-muted">Uploaded <%= time_ago_in_words product.created_at %> ago</small></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  document.getElementById("nav_listings").classList.add("active")
</script>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

<script>
    document.getElementById("nav_new_listing").classList.add("active")
</script>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<%= link_to "Rent this hut", new_rental_path(product_id: @product), class:"btn btn-success" %>

<hr>
<div class="container-fluid p-2 p-md-4">
  <div id="btn_add_comment">
    <%= button_to "Add a comment", new_comment_path(product_id: @product), class:"btn btn-primary", method: :post%>
  </div>

  <h5 class="my-3">Comments (<%= @product.comments.count %>)</h5>

  <div id="comments">
    <% @product.comments.reverse_each do |comment|%>
      <%= render comment %>
    <% end %>

    <% if @product.comments.count == 0%>
      <h6>This listing has no comments yet</h6>
    <% end %>
  </div>
</div>