config/routes.rb
Rails.application.routes.draw do
  resources :rentals
  resources :comments do
    member do
      post :new
    end
  end
  resources :products

  devise_for :users

  get "profile/:id", to: "profile#profile", as: "profile"
  get "profile/:id/rentals", to: "profile#rentals", as: "profile_rentals"
  post "rental/done/:id", to: "rentals#set_done", as: "rental_done"
  post "like/:product_id", to: "like#create", as: "like"
  post "dislike/:product_id", to: "dislike#create", as: "dislike"

  get "home", to: "home#index", as: "home"

  # Defines the root path route ("/")
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :product, dependent: :destroy
end

app/models/dislike.rb
class Dislike < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord

  has_one_attached :image, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_many :rentals, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy

  validate :acceptable_image


  def acceptable_image
    Rails.logger.debug "Sjekker om det er attached"
    if image.attached?
      Rails.logger.debug "Bildet er attached"
      acceptable_types = ["image/jpeg", "image/jpg", "image/png"]

      unless acceptable_types.include?(image.content_type)
        errors.add(:main_image, "must be a JPEG or PNG")
      end
    else
      self.image.attach(io: File.open(Rails.root.join("app", "assets", "images", "default.png")), filename: 'default.png' , content_type: "image/png  ")
    end
  end


end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :product

  enum :status, {
    pending: 0,
    active: 1,
    done: 2
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :rentals, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy

  def full_name
    first_name + " " + last_name
  end

end

app/controllers/dislike_controller.rb
class DislikeController < ApplicationController

  def create
    product = Product.find(params[:product_id])
    @dislike = product.dislikes.build
    @dislike.user = current_user
    @dislike.save
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  before_action :authenticate_user!


  def create
    product = Product.find(params[:product_id])
    @like = product.likes.build
    @like.user = current_user
    @like.save
  end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :set_profile

  def profile

  end

  def rentals

  end

  private

  def set_profile
    @user = User.find(params[:id])
  end

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_rental, only: %i[ show edit update destroy set_done ]

  # GET /rentals or /rentals.json
  def index
    @rentals = Rental.all
  end

  # GET /rentals/1 or /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    product = Product.find(params[:product_id])
    @rental = product.rentals.new
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals or /rentals.json
  def create
    @rental = current_user.rentals.new(rental_params)

    if @rental.start_date == Date.current
      Rails.logger.debug "Today!! Set to active"
      @rental.active!
    end

    respond_to do |format|
      if @rental.save
        format.html { redirect_to rental_url(@rental), notice: "Rental was successfully created." }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1 or /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to rental_url(@rental), notice: "Rental was successfully updated." }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1 or /rentals/1.json
  def destroy
    @rental.destroy

    respond_to do |format|
      format.html { redirect_to rentals_url, notice: "Rental was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def set_done
    @rental.done!
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.remove(@rental),
          turbo_stream.prepend("done-rentals", @rental),
          turbo_stream.update("active-count", partial:"rentals/active_rentals_counter", locals:{active: @rental.user.rentals.where(status: :active)}),
          turbo_stream.update("done-count", partial:"rentals/done_rentals_counter", locals:{done: @rental.user.rentals.where(status: :done)}),
          turbo_stream.update("modal-body", partial: "rentals/rate_rental", locals:{rental: @rental})
        ]
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rental_params
      params.require(:rental).permit(:user_id, :product_id, :start_date, :end_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dislike_helper.rb
module DislikeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background-color: #e3f2fd;" >
  <div class="container py-2">
    <h3 style="font-family: 'Dancing Script', serif" class="px-2"><%= link_to "RentAHut", root_path, class:"navbar-brand"%></h3>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Listings", products_path, class:"nav-link", id:"nav_listings" %>
        <%= link_to "Create a listing", new_product_path, class:"nav-link", id:"nav_new_listing" %>

        <% if user_signed_in? %>
          <%= link_to "Profile", profile_path(current_user), class:"nav-link", id:"nav_my_profile" %>
          <%= link_to "My rentals", profile_rentals_path(current_user), class:"nav-link", id:"nav_my_rentals" %>
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, form_class:"nav-link" %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: "nav-link", style:"color:#8d7d37" %>
        <% end %>
      </div>
    </div>

  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackathon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Google material icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" >
  </head>

  <body>

  <%= render "layouts/navbar" %>

    <div class="container mb-4" id="contains-all">
      <div class="row">
        <div class="col-0 col-md-1 ">

        </div>

        <div class="col">
          <%= yield %>
        </div>

        <div class="col-md-1">

        </div>
      </div>

    </div>

  <div id="modal-div">
    <div class="modal fade" id="modal" tabindex="-1" aria-labelledby="exampleModalLabel">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Rate this rental</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body" id="modal-body">

          </div>

        </div>
      </div>
    </div>
  </div>



  </body>
</html>